### ISSUE TITLE
[Feature]: Make weather notifications show via phone

### ISSUE THREAD

**Issue by GarrettOC95** [nyx-servers/Issue-Tracker#30]
### Contact Details

goco

### What should we add?

A thing that annoyed a lot of people before was the constant spam of un-immersive popups of the change in weather in chat kept popping up. However as apposed to completely removing them, changing them to a phone notification would be much more immersive and less intrusive to RP.

### Relevant Parties

Everyone

**Comment by JamesSc0tt** [comment]
![image](https://github.com/nyx-servers/Issue-Tracker/assets/24981581/46ba1e4c-88bf-41fe-87de-f2ee79a77cf6)

**Comment by JamesSc0tt** [comment]
also fixed character
