### ISSUE TITLE
[Bug]: Spawn Location Name is displayed as "SUBVERSION"

### ISSUE THREAD

**Issue by DivineZ23** [nyx-servers/Issue-Tracker#65]
### Contact Details

divine1337

### What happened?

![Screenshot (18)](https://github.com/nyx-servers/Issue-Tracker/assets/87801591/66fd9c6b-50d0-4c78-a0bf-a63df0822fa0)

PFA for more info on the issue. You can see the spawn location name is shown as "Subversion" instead of MRPD or NYX or something else.

### Severity impact

Severity:High

**Comment by JamesSc0tt** [comment]
duplicate: https://github.com/nyx-servers/Issue-Tracker/issues/51
