### ISSUE TITLE
[Feature]: More immersive towing job

### ISSUE THREAD

**Issue by SpoookyLoL** [nyx-servers/Issue-Tracker#75]
### Contact Details

Spoooky

### What should we add?

In SV's last rendition when the tow job got introduced to the server it was a unique, fun, and immersive experience. Upon starting the job you received a tow truck remote to control the flatbed and winch. So when you arrived at the vehicle to repo you would lower the flatbed so it became like a ramp, then you third-eyed the winch to pick up the hook and you could see the hook in your hand as well as the rope from the winch. You then took it over to the vehicle and third-eyed it to attach the hook. You could then either third-eye the winch or use the remote to reel the vehicle onto the ramp. Once the vehicle had been reeled in, you could use the remote or third-eye the vehicle to clamp it down, then using the remote or third-eyeing the side of the truck you would raise the flatbed back to its original state with the vehicle clamped and drive it to the destination.

A lot of the players that experienced really enjoyed it 

### Relevant Parties

Everyone

**Comment by SpoookyLoL** [comment]
The latest version was the removal of the features mentioned above as it was very buggy, and I guess too much time was spent getting it in so they didn't want to commit more time to fixing the bugs so the features were removed, making it more like a generic tow script.

**Comment by JamesSc0tt** [comment]
Replaced the tow job with the original tow job I made.
